apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
  labels:
    app: back-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: back
        image: sky0akash/tata_portal_backend
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: back-service
spec:
  selector:
    app: back
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30002  # You can choose any available node port
  type: LoadBalancer  # Change the type to NodePort

